### ISSUE TITLE
standardized partition layouts

### ISSUE THREAD

**Issue by MayNiklas** [lounge-rocks/the-lounge#16]
Right now, we are kind of restructuring a lot of our infrastructure.
Most hosts will be completely replaced.
We are now using nix-anywhere + disko to deploy our hosts.

I would suggest the following layout for all hosts:
```nix
  disko.devices.disk.main = {
      type = "disk";
      device = "/dev/vda";
      content = {
        type = "table";
        format = "gpt";
        partitions = [
          {
            name = "boot";
            start = "0";
            end = "1M";
            flags = [ "bios_grub" ];
          }
          {
            name = "ESP";
            start = "1M";
            end = "512M";
            bootable = true;
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
            };
          }
          {
            name = "nixos";
            start = "512M";
            end = "100%";
            content = {
              type = "filesystem";
              format = "ext4";
              mountpoint = "/";
            };
          }
        ];
      };
    };
 ```
This would allow the following:
```nix
    boot.loader.grub = {
      devices = [ "/dev/sda" ];
      efiSupport = true;
      efiInstallAsRemovable = true;
    };
```
-> EFI and BIOS boot!
We will have to support EFI as well as BIOS boot, since some providers only support one or the other.
Each host having both partitions would allow us to completely standardize our boot loader within our generalized cloud-provider module.

The huge disadvantage of this change:
We have to reformat / redeploy all current hosts, using the old layouts.
In my opinion this is worth it: it would only affect stuart:
* the other hosts will be redeployed anyway
* stuart currently has a 98M boot partition -> we can't safely upgrade stuart -> redeploying it with a different partition layout is something we should do anyway (my personal opinion)

Is this something we can agree on?
If so, I would implement the changes and test each provider / architecture until everything makes sense.

I would suggest we figure out our provider specific configs before deploying our new hosts.
If we don't, changing partitions afterwards could be difficult / impossible without redeploying.

**Comment by pinpox** [comment]
> This would allow the following:
> 
> ```nix
>     boot.loader.grub = {
>       devices = [ "/dev/sda" ];
>       efiSupport = true;
>       efiInstallAsRemovable = true;
>     };
> ```

Wouldn't this be `"/dev/vda"` then instead of `sda`?

**Comment by MayNiklas** [comment]
> > This would allow the following:
> > ```nix
> >     boot.loader.grub = {
> >       devices = [ "/dev/sda" ];
> >       efiSupport = true;
> >       efiInstallAsRemovable = true;
> >     };
> > ```
> 
> Wouldn't this be `"/dev/vda"` then instead of `sda`? Otherwise: fine for me.

It depends:
Currently we only have /dev/vda implemented on Promox (needs support from the host).
For this reason, I implemented a variable that defaults to /dev/sda - but was set to /dev/vda for Hetzner.

**Comment by MayNiklas** [comment]
Got implemented.
We still use legacy disko layout -> future todo
